фундаментальные реализации + схема
nessai1/gophKeeper pull request #1
Opened 2024-03-03 18:29 UTC by nessai1

2024-03-03 18:42 UTC, nessai1 commented
Был сделан фундаментальный функционал. keeper - клиент, service - сервер.

Сервис и кипер общаются по gRPC. Авторизация планируется через метаданные по OAuth (сейчас ей и занимаюсь)

Все данные юзера (пароли, логины, текста, бинарники итд. хранятся в одном бакете s3, бакет один для всех юзеров). Метаданные (логин,пароль юзера и данные об объектах s3 и их отношении к юзерам) хранятся в psql 

Успел реализовать коннект к s3, наладил общение gRPC, почти реализовал коннект к постгре (сделана миграция)

Сейчас на этапе регистрации/автоизации. После этого буду делать отправку чувствительных данных и их шифрование на сервере. Плюс надо написать тесты и доку


Схема приложения в scheme.drawio

Скринами сюда закину если не удобно открывать

Общая концепция
![Screenshot from 2024-03-03 20-39-33](https://github.com/nessai1/gophKeeper/assets/31453715/563b905e-8237-4291-b194-475cbc550737)

Клиентская часть

![Screenshot from 2024-03-03 20-40-43](https://github.com/nessai1/gophKeeper/assets/31453715/b3d93660-db7a-4a23-8766-bfebe8be8a0c)


Серверная часть (там же снизу схема БД)

![Screenshot from 2024-03-03 20-41-38](https://github.com/nessai1/gophKeeper/assets/31453715/def01e22-82c7-417f-b21c-8bc23569aa3e)



CLI (keeper) выглядит так
![Screenshot from 2024-03-03 20-34-45](https://github.com/nessai1/gophKeeper/assets/31453715/b052b5c4-2b27-4e65-930c-dc4ce7f50d50)

2024-03-04 17:02 UTC, kilchik reviewed
По структуре - ОК. По схеме - ОК
Меня только смущает, что ты хочешь все данные хранить в s3, я бы предложил для s3 оставить только бинарные данные, для всего остального не вижу причины не использовать БД

2024-03-04 17:02 UTC, kilchik commented on internal/keeper/connector/grpc.go
> +	conn, err := grpc.Dial(serviceAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
Не забудь про TLS

2024-03-04 17:02 UTC, kilchik commented on internal/keeper/performer/help.go
> +	for _, val := range AvailablePerformers {
Здесь все-таки мапу я бы ожидал

2024-03-10 18:11 UTC, nessai1 commented
Новая схема сервера

![Screenshot from 2024-03-10 20-08-52](https://github.com/nessai1/gophKeeper/assets/31453715/daa9bed3-aec7-453c-888c-bf7a8728aeaa)


Только успел подойти к реализации шифрования и отправки данных. до вторника-среды добить базовые реализации шифрования&отправки данных+правки по твоим комментариям

2024-03-10 20:04 UTC, kilchik requested changes

2024-03-10 20:04 UTC, kilchik commented on Makefile
> +	GOOS=windows GOARCH=amd64 go build -o keeper/keeper.exe -ldflags "-X main.Commit=$(COMMIT) -X 'main.BuildTime=$(BUILD_DATE)' -X main.Version=$(VERSION)" cmd/keeper/main.go
Чтобы избежать дублирования, можешь сделать подкомманду build, в которую будет передаваться переменная OS

2024-03-10 20:04 UTC, kilchik commented on api/proto/keeperserver.proto
> +  IN_PROGRESS = 1;
Т е клиенту может вернуться PENDING при заливке? Как узнает, что заливка завершена?

2024-03-10 20:04 UTC, kilchik commented on internal/keeper/performer/secret.go
> +	-- For media it find file in media dir by name and upload it on server
Почему бы не позволить загружать файл из любого места по абсолютному пути? Иначе пользователю каждый раз придется переносить файл в специальную папку, о которой он может и не знать

2024-03-10 20:04 UTC, kilchik commented on migrations/psql/002_create_secret_metadata_table.up.sql
> +CREATE INDEX secret_metadata_owner_uuid ON secret_metadata (owner_uuid);
Если запрос будет по имени секрета, может сделать составной индекс?

2024-03-16 18:57 UTC, nessai1 commented on internal/keeper/performer/secret.go
> +	-- For media it find file in media dir by name and upload it on server
done!

2024-03-16 19:01 UTC, nessai1 commented on migrations/psql/002_create_secret_metadata_table.up.sql
> +CREATE INDEX secret_metadata_owner_uuid ON secret_metadata (owner_uuid);
Да, правда. Добавил

2024-03-18 01:13 UTC, nessai1 commented
Базовый флоу реализован.

Не успел отреагировать на все замечания, буду прихорашивать код, присать тесты  и править еще неотвеченные моменты :)

2024-03-18 09:57 UTC, nessai1 commented on api/proto/keeperserver.proto
> +  IN_PROGRESS = 1;
А это я нашел какой-то индусский гайд по заливке файлов. В итоге сам разобрался в работе стриминга и понял что это не нужно. Убрал

2024-03-22 10:01 UTC, nessai1 commented on internal/keeper/connector/grpc.go
> +	conn, err := grpc.Dial(serviceAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
done!

2024-03-22 10:25 UTC, nessai1 commented on internal/keeper/performer/help.go
> +	for _, val := range AvailablePerformers {
done!

2024-03-22 10:53 UTC, nessai1 commented on Makefile
> +	GOOS=windows GOARCH=amd64 go build -o keeper/keeper.exe -ldflags "-X main.Commit=$(COMMIT) -X 'main.BuildTime=$(BUILD_DATE)' -X main.Version=$(VERSION)" cmd/keeper/main.go
done!

2024-03-23 10:10 UTC, kilchik requested changes

2024-03-23 10:10 UTC, kilchik commented on internal/keeper/connector/grpc.go
> +			f.Close()
Close должен вызываться и при отсутствии ошибок, иначе клиент может упереться в число открытых файловых дескрипторов

2024-03-23 10:10 UTC, kilchik commented on internal/keeper/keeper.go
> +func (a *Application) getPerformers() {
Это лишнее?

2024-03-23 10:10 UTC, kilchik commented on internal/keeper/media/media.go
> +const ContentSectionSize = 256
Если константы предполагается использовать только в текущем пакете, их следует сделать неэкспортируемыми

2024-03-23 10:10 UTC, kilchik commented on internal/keeper/performer/ping.go
> +	answer, err := conn.Ping(context.TODO())
Здесь должен быть какой-нибудь таймаут

2024-03-23 10:10 UTC, kilchik commented on internal/keeper/performer/ping.go
> +		fmt.Printf("Answer: %s\n", answer)
else не нужен

2024-03-23 10:10 UTC, kilchik commented on internal/keeper/performer/secret.go
> +	ctx := context.TODO()
Нужно предусмотреть таймауты, а лучше предусмотреть graceful shutdown клиента, т е обработать корректно Ctrl+C от пользователя

2024-03-23 10:10 UTC, kilchik commented on internal/keeper/performer/secret.go
> +	if secretType == SecretTypeMedia {
switch сильно упростит конструкцию

2024-03-23 10:10 UTC, kilchik commented on internal/keeper/performer/secret_media.go
> +	copyFile, err := os.Create(filepath.Join(p.workDir, "media", filepath.Base(name)))
Зачем нам локальная копия файла?

2024-03-23 10:10 UTC, kilchik commented on internal/service/auth.go
> +	hash := sha256.Sum256([]byte(pwd + "myGophkeeperSaltlol"))
Соль в конфиг

2024-03-23 10:10 UTC, kilchik commented on internal/service/handlers_auth.go
> +		s.logger.Info("Duplicate registration", zap.String("login", request.Login))
Гарантировать уникальность чего-то в базе всегда следует через добавление ограничения на дубликат в схему и обработку duplicate key ошибки. Иначе мы никогда не сможем рассчитывать на атомарность такой операции

2024-03-23 10:10 UTC, kilchik commented on internal/service/handlers_media.go
> +		err = s.mediaStorage.Delete(stream.Context(), dbMetadata.UUID)
Все операции над mediaStorage должны выполнять в транзакции, иначе мы не можем гарантировать консистентности данных

2024-03-23 10:10 UTC, kilchik commented on internal/service/handlers_media.go
> +		err = s.plainStorage.RemoveSecretByUUID(context.TODO(), dbMetadata.UUID)
Представь, что сервер умрет до выполнения RemoveSecretByUUID - данные будут неконсистентными. Подумай, как лучше добиться транзакционности заливки файла + обновления метаданных, не блокируя сильно таблицу для параллельных загрузок

2024-03-23 10:10 UTC, kilchik commented on internal/service/plainstorage/plainstorage_psql.go
> +	for rows.Next() {
sqlx позволяет сильно упростить код для select в слайс. Посмотри, например, здесь https://jmoiron.github.io/sqlx/#namedParams

2024-03-23 10:33 UTC, nessai1 commented on internal/keeper/connector/grpc.go
> +			f.Close()
Он потом и закрывается: internal/keeper/performer/secret_media.go:92

Функция записывает данные и отдает открытый дескриптор с этими данными

2024-03-23 10:33 UTC, nessai1 commented on internal/keeper/keeper.go
> +func (a *Application) getPerformers() {
Ага :) 
Убрал

2024-03-23 10:37 UTC, nessai1 commented on internal/keeper/media/media.go
> +const ContentSectionSize = 256
Done!

2024-03-23 10:41 UTC, nessai1 commented on internal/keeper/media/media.go
> +const ContentSectionSize = 256
Done!

2024-03-23 10:41 UTC, nessai1 commented on internal/keeper/performer/ping.go
> +	answer, err := conn.Ping(context.TODO())
Done!

2024-03-23 10:42 UTC, nessai1 commented on internal/keeper/performer/ping.go
> +		fmt.Printf("Answer: %s\n", answer)
done!

2024-03-23 10:44 UTC, nessai1 commented on internal/keeper/performer/ping.go
> +	answer, err := conn.Ping(context.TODO())
done!

2024-03-23 10:44 UTC, nessai1 commented on internal/keeper/performer/ping.go
> +		fmt.Printf("Answer: %s\n", answer)
done!

2024-03-23 13:09 UTC, nessai1 commented on internal/service/handlers_auth.go
> +		s.logger.Info("Duplicate registration", zap.String("login", request.Login))
Done!

2024-03-23 13:36 UTC, nessai1 commented on internal/service/handlers_auth.go
> +		s.logger.Info("Duplicate registration", zap.String("login", request.Login))
Done!

2024-03-23 13:39 UTC, nessai1 commented on internal/service/handlers_media.go
> +		err = s.plainStorage.RemoveSecretByUUID(context.TODO(), dbMetadata.UUID)
Кажется что лучше будет создавать запись в БД уже после полной загрузки медиа, просто надо генерить UUID на стороне обработчика. Переделаю на такой способ

2024-03-23 16:58 UTC, nessai1 commented on internal/service/plainstorage/plainstorage_psql.go
> +	for rows.Next() {
done!

2024-03-24 10:01 UTC, nessai1 commented on internal/service/handlers_media.go
> +		err = s.mediaStorage.Delete(stream.Context(), dbMetadata.UUID)
Тут сделал не замену медиа, а создание нового медиа с новым UUID. В обработчике удаления метода сделал транзакцию

2024-03-24 10:02 UTC, nessai1 commented on internal/service/auth.go
> +	hash := sha256.Sum256([]byte(pwd + "myGophkeeperSaltlol"))
Done!

2024-03-25 18:02 UTC, kilchik approved these changes

2024-03-27 04:52 UTC, merged